# Generated by Django 3.0.7 on 2020-07-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='commit',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
